name: CI

on:
  pull_request:
  push:
    tags-ignore:
      - v*

jobs:

  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        scala:
          - scala211
          - scala212
          - scala213
          - scala3
    steps:

      - uses: actions/checkout@v2

      - name: Setup Scala
        uses: japgolly/setup-everything-scala@v2.0

      - name: Build and test
        run: sbt++field ${{ matrix.scala }} -DCI=1 test package doc

      - name: Validate formatting
        run: sbt++field ${{ matrix.scala }} -DCI=1 dom/scalafmtCheck

      - name: Validate api report
        if: matrix.scala != 'scala211' && matrix.scala != 'scala3'
        run: ./api-reports/validate $(sbt-const ${{ matrix.scala }})

  readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: japgolly/setup-everything-scala@v2.0
      - name: Readme generation
        run: sbt readme/run
